### ISSUE TITLE
Vad filter 'list index out of range' chunk_index 

### ISSUE THREAD

**Issue by jordimas** [guillaumekln/faster-whisper#106]
faster-whisper 0.4.0

The vad filter sometimes produces an exception. 

You can reproduce it by doing _whisper-ctranslate2 vad2.flac --model large-v2 --vad_filter True_

The file is here [vad2.flac](https://github.com/jordimas/calaix-de-sastre/raw/master/faster-whisper/vad2.flac)

The same file with _medium_ model for example does not trigger the problem, I guess timestamp prediction is different and does not trigger the bug.

Traceback (most recent call last):
  File "/home/jordi/.local/bin/whisper-ctranslate2", line 8, in <module>
    sys.exit(main())
  File "/home/jordi/.local/lib/python3.10/site-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 320, in main
    result = Transcribe().inference(
  File "/home/jordi/.local/lib/python3.10/site-packages/src/whisper_ctranslate2/transcribe.py", line 131, in inference
    for segment in segments:
  File "/home/jordi/.local/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 729, in restore_speech_timestamps
    end=ts_map.get_original_time(segment.end),
  File "/home/jordi/.local/lib/python3.10/site-packages/faster_whisper/vad.py", line 206, in get_original_time
    total_silence_before = self.total_silence_before[chunk_index]
IndexError: list index out of range

**Comment by guillaumekln** [comment]
Thank you for reporting. I will make a new version tomorrow. Maybe we can catch other errors like this one.

**Comment by jordimas** [comment]
Thanks so much for the quick fix!
