### ISSUE TITLE
Is it possible to use python cuda libraries from a virtual env? Origianal whisper is super easy to install since it doesn't require me to change my system cuda version and simply pulls in the needed libs using pip.

### ISSUE THREAD

**Issue by Gobz** [guillaumekln/faster-whisper#153]
```
Traceback (most recent call last):
  File "/home/gobz/AI/talkMiku/talkMiku.py", line 13, in <module>
    segments, info = model.transcribe("audio.mp3", beam_size=5)
  File "/home/gobz/AI/talkMiku/whisper/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 238, in transcribe
    encoder_output = self.encode(segment)
  File "/home/gobz/AI/talkMiku/whisper/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 483, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library libcublas.so.11 is not found or cannot be loaded
```

Not that the error is super interesting, but this is where I stand currently.

**Comment by guillaumekln** [comment]
Currently you can already make use of these libraries but you need to manually set the environment variable `LD_LIBRARY_PATH` before running Python. I verified that the following works:

```bash
pip install nvidia-cublas-cu11 nvidia-cudnn-cu11

export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
```

(Note that this only works on Linux systems.)

I will look if we can load these libraries automatically when they are installed. It's an improvement we should make in the underlying CTranslate2 library.

**Comment by archive-r** [comment]
> Currently you can already make use of these libraries but you need to manually set the environment variable `LD_LIBRARY_PATH` before running Python. I verified that the following works:
> 
> ```shell
> pip install nvidia-cublas-cu11 nvidia-cudnn-cu11
> 
> export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
> ```
> 
> (Note that this only works on Linux systems.)
> 
> I will look if we can load these libraries automatically when they are installed. It's an improvement we should make in the underlying CTranslate2 library.

Is it possible to get it to work with VENV on Windows by any chance? I have cuda 11.8, cudnn 11.x all installed properly, but it's not working. would installing pytorch help?

**Comment by guillaumekln** [comment]
This solution does not work on Windows because NVIDIA only provides Linux binaries for the cuDNN package:

https://pypi.org/project/nvidia-cudnn-cu11/#files

Installing PyTorch will not help in this case.

> I did everything, including cuda 11.8 installation, cudnn 11.x installation, zlib installation, and path addition, but I don't know why this is happening.

Maybe you should double-check the PATH setting. I know it can be tricky to get it right.

You could also look at @Purfview's standalone executable: https://github.com/Purfview/whisper-standalone-win. There you can download the NVIDIA libraries and simply put them in the same directory as the executable.

**Comment by archive-r** [comment]
> This solution does not work on Windows because NVIDIA only provides Linux binaries for the cuDNN package:
> 
> https://pypi.org/project/nvidia-cudnn-cu11/#files
> 
> Installing PyTorch will not help in this case.
> 
> > I did everything, including cuda 11.8 installation, cudnn 11.x installation, zlib installation, and path addition, but I don't know why this is happening.
> 
> Maybe you should double-check the PATH setting. I know it can be tricky to get it right.
> 
> You could also look at @Purfview's standalone executable: https://github.com/Purfview/whisper-standalone-win. There you can download the NVIDIA libraries and simply put them in the same directory as the executable.

Thanks, I'll try again to make sure I'm not missing anything. 
I just have one question: is the installation of cuda, cunnn "essential" for running faster-whisper on a gpu?
I don't remember installing cudnn (before the windows reinstall), but only because device="cuda" just worked fine.
If they are required to be installed, my memory is probably wrong.

**Comment by guillaumekln** [comment]
Yes these libraries are required for GPU execution. An error is raised when you try to use the GPU but these libraries cannot be found.

**Comment by yangyaofei** [comment]
According to this solution, I get the code below:

```python
try:
    import os
    import nvidia.cublas.lib
    import nvidia.cudnn.lib

    cublas_path = os.path.dirname(nvidia.cublas.lib.__file__)
    cudnn_path = os.path.dirname(nvidia.cudnn.lib.__file__)
    os.environ["LD_LIBRARY_PATH"] = f"{cublas_path}:{cudnn_path}"
except ModuleNotFoundError:
    pass
```

But still get same error, like the PATH is not set.

**Comment by guillaumekln** [comment]
The environment variable `LD_LIBRARY_PATH` should be set **before** starting the Python process.

**Comment by Feanix-Fyre** [comment]
I'm pretty certain that NVIDIA offers cuDNN files of some sort for Windows at https://developer.nvidia.com/rdp/cudnn-download. I do remember getting faster-whisper to work on the GPU on Windows but I do remember it being quite the hassle, either due to my inexperience or genuine difficulty.

**Comment by lugia19** [comment]
If you're on Windows, a functioning workaround I've found is to install torch with cuda support, then add the "lib" subfolder to your PATH.

It works since the lib folder contains DLLs for both cuBLAS and cuDNN.

**Comment by vadi2** [comment]
The trick in https://github.com/guillaumekln/faster-whisper/issues/153#issuecomment-1510218906 is not working for me, what am I doing wrong?

```python
(faster-whisper) vadi@barbar:~$ pip install nvidia-cublas-cu11 nvidia-cudnn-cu11
Requirement already satisfied: nvidia-cublas-cu11 in ./Programs/miniconda3/envs/faster-whisper/lib/python3.10/site-packages (11.11.3.6)
Requirement already satisfied: nvidia-cudnn-cu11 in ./Programs/miniconda3/envs/faster-whisper/lib/python3.10/site-packages (8.9.2.26)
(faster-whisper) vadi@barbar:~$ export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
(faster-whisper) vadi@barbar:~$ echo $LD_LIBRARY_PATH 
/home/vadi/Programs/miniconda3/envs/faster-whisper/lib/python3.10/site-packages/nvidia/cublas/lib:/home/vadi/Programs/miniconda3/envs/faster-whisper/lib/python3.10/site-packages/nvidia/cudnn/lib
(faster-whisper) vadi@barbar:~$ python ~/Downloads/faster-whisper.py 
Traceback (most recent call last):
  File "/home/vadi/Downloads/faster-whisper.py", line 6, in <module>
    model = WhisperModel(model_size, device="cuda", compute_type="float16")
  File "/home/vadi/Programs/miniconda3/envs/faster-whisper/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 124, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error unknown error
(faster-whisper) vadi@barbar:~$ 
```

Running Nvidia driver 535.54.03 on RTX 4080 on Ubuntu 22.04.

**Comment by guillaumekln** [comment]
This is probably another issue. I think it happens when the GPU driver is not loaded correctly (e.g. it was just updated to a new version). Rebooting the system will often fix this type of error.

**Comment by vadi2** [comment]
It did. Thanks!

**Comment by Simon-chai** [comment]
> ```shell
> nvidia.cublas.lib.__file__
> ```

why my nvidia.cublas.lib.__file__ attribute is None so the environment variable failed to set,and when i run faster_whisper and will encounter the error 
"Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!"

**Comment by guillaumekln** [comment]
The error is about cuDNN, not cuBLAS.

You should double-check that you correct installed the pip packages as shown in https://github.com/guillaumekln/faster-whisper/issues/153#issuecomment-1510218906.

**Comment by s-h-a-d-o-w** [comment]
> Currently you can already make use of these libraries but you need to manually set the environment variable `LD_LIBRARY_PATH` before running Python. I verified that the following works:
> 
> ```shell
> pip install nvidia-cublas-cu11 nvidia-cudnn-cu11
> 
> export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
> ```
> 
> (Note that this only works on Linux systems.)
> 
> I will look if we can load these libraries automatically when they are installed. It's an improvement we should make in the underlying CTranslate2 library.

Doesn't work for me on Ubuntu (WSL).

`__file__` doesn't exist:

```
>>> print(nvidia.cublas.lib.__file__)
None
```

But the libraries are installed:
```
andy@work:~$ pip install nvidia-cublas-cu11 nvidia-cudnn-cu11
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nvidia-cublas-cu11 in ./.local/lib/python3.8/site-packages (11.10.3.66)
Requirement already satisfied: nvidia-cudnn-cu11 in ./.local/lib/python3.8/site-packages (8.5.0.96)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from nvidia-cublas-cu11) (68.2.2)
Requirement already satisfied: wheel in ./.local/lib/python3.8/site-packages (from nvidia-cublas-cu11) (0.40.0)
```

```
>>> import os; import nvidia.cublas.lib; import nvidia.cudnn.lib;
>>> print(nvidia.cublas.lib)
<module 'nvidia.cublas.lib' (namespace)>
```

Setting the paths manually like so worked:
```
export LD_LIBRARY_PATH="$HOME/.local/lib/python3.8/site-packages/nvidia/cublas/lib/:$HOME/.local/lib/python3.8/site-packages/nvidia/cudnn/lib/"
```

**Comment by pauloboritza** [comment]
> > Atualmente você já pode fazer uso dessas bibliotecas, mas precisa definir manualmente a variável de ambiente `LD_LIBRARY_PATH`antes de executar o Python.  Verifiquei que o seguinte funciona: 
> > ```shell
> > pip install nvidia-cublas-cu11 nvidia-cudnn-cu11
> > 
> > export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (Observe que isso só funciona em sistemas Linux.) 
> > Vou verificar se podemos carregar essas bibliotecas automaticamente quando elas forem instaladas.  É uma melhoria que devemos fazer na biblioteca CTranslate2 subjacente.
> 
> Por acaso é possível fazê-lo funcionar com VENV no Windows? Tenho cuda 11.8, cudnn 11.x todos instalados corretamente, mas não está funcionando.
> 
> ```
> Could not load library cudnn_cnn_infer64_8.dll. Error code 126
> Please make sure cudnn_cnn_infer64_8.dll is in your library path!
> ```
> 
> instalar o pytorch ajudaria?
> 
> O que é realmente estranho é que, há alguns dias, funcionou bem sem qualquer instalação de CUDA, CUDNN, zlib. Depois de uma instalação limpa do Windows, não funciona.
> 
> editado: O mesmo erro ocorre mesmo em um ambiente não virtual. Fiz tudo, incluindo instalação do cuda 11.8, instalação do cudnn 11.x, instalação do zlib e adição de caminho, mas não sei por que isso está acontecendo.

Solve erro in Windows 
```
....
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded
```
download https://github.com/Purfview/whisper-standalone-win/releases/download/libs/cuBLAS.and.cuDNN_win_v3.zip
unizip *.dll in project path 
add lines in the app:
```
import ctypes
cublas64_11 = ctypes.WinDLL('.\cublas64_11.dll')
```

**Comment by pauloboritza** [comment]
> > This solution does not work on Windows because NVIDIA only provides Linux binaries for the cuDNN package:
> > https://pypi.org/project/nvidia-cudnn-cu11/#files
> > Installing PyTorch will not help in this case.
> > > I did everything, including cuda 11.8 installation, cudnn 11.x installation, zlib installation, and path addition, but I don't know why this is happening.
> > 
> > 
> > Maybe you should double-check the PATH setting. I know it can be tricky to get it right.
> > You could also look at @Purfview's standalone executable: https://github.com/Purfview/whisper-standalone-win. There you can download the NVIDIA libraries and simply put them in the same directory as the executable.
> 
> Thanks, I'll try again to make sure I'm not missing anything. I just have one question: is the installation of cuda, cudnn "essential" for running faster-whisper on a gpu? I don't remember installing cudnn (before the windows reinstall), but only because `device="cuda"` just worked fine. If they are required to be installed, my memory is probably wrong.

Error in Windows 
```
....
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded
```
download https://github.com/Purfview/whisper-standalone-win/releases/download/libs/cuBLAS.and.cuDNN_win_v3.zip
unizip *.dll in project path 
add lines in the app:
```
import ctypes
cublas64_11 = ctypes.WinDLL('.\cublas64_11.dll')
```

**Comment by lugia19** [comment]
> > If you're on Windows, a functioning workaround I've found is to install torch with cuda support, then add the "lib" subfolder to your PATH.
> > It works since the lib folder contains DLLs for both cuBLAS and cuDNN.
> 
> It's been a while, but what command did you use to install torch specifically?

Oh, it was just the usual `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` type deal.

Just installing torch with CUDA.

**Comment by BBC-Esq** [comment]
> > Currently you can already make use of these libraries but you need to manually set the environment variable `LD_LIBRARY_PATH` before running Python. I verified that the following works:
> 
> > 
> 
> > ```shell
> 
> > pip install nvidia-cublas-cu11 nvidia-cudnn-cu11
> 
> > 
> 
> > export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
> 
> > ```
> 
> > 
> 
> > (Note that this only works on Linux systems.)
> 
> > 
> 
> > I will look if we can load these libraries automatically when they are installed. It's an improvement we should make in the underlying CTranslate2 library.
> 
> 
> 
> Hi @guillaumekln , may I know if this improvement has been made on CTranslate2? I'm using CUDA 12.1 and I'm facing the same issue. It works by exporting the `LD_LIBRARY_PATH` env variable though.
> 
> 
> 
> Happy to help for anything you'd need.

Yes, look at my gui.pi script. 

https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio

**Comment by BBC-Esq** [comment]
Here's a sample function that works if you are "pip" installing the necessary cuda and/or cudnn libraries.  It also includes triton, which you can disregard if need be:

```
def set_cuda_paths():
    import sys
    import os
    from pathlib import Path
    venv_base = Path(sys.executable).parent.parent
    nvidia_base_path = venv_base / 'Lib' / 'site-packages' / 'nvidia'
    cuda_path_runtime = nvidia_base_path / 'cuda_runtime' / 'bin'
    cuda_path_runtime_lib = nvidia_base_path / 'cuda_runtime' / 'lib' / 'x64'
    cuda_path_runtime_include = nvidia_base_path / 'cuda_runtime' / 'include'
    cublas_path = nvidia_base_path / 'cublas' / 'bin'
    cudnn_path = nvidia_base_path / 'cudnn' / 'bin'
    nvrtc_path = nvidia_base_path / 'cuda_nvrtc' / 'bin'
    nvcc_path = nvidia_base_path / 'cuda_nvcc' / 'bin'
    paths_to_add = [
        str(cuda_path_runtime),
        str(cuda_path_runtime_lib),
        str(cuda_path_runtime_include),
        str(cublas_path),
        str(cudnn_path),
        str(nvrtc_path),
        str(nvcc_path),
    ]
    current_value = os.environ.get('PATH', '')
    new_value = os.pathsep.join(paths_to_add + ([current_value] if current_value else []))
    os.environ['PATH'] = new_value

    triton_cuda_path = nvidia_base_path / 'cuda_runtime'
    current_cuda_path = os.environ.get('CUDA_PATH', '')
    new_cuda_path = os.pathsep.join([str(triton_cuda_path)] + ([current_cuda_path] if current_cuda_path else []))
    os.environ['CUDA_PATH'] = new_cuda_path
```

**Comment by XXXXRT666** [comment]
```
def load_cudnn():
    import torch

    if not torch.cuda.is_available():
        print("[INFO] CUDA is not available, skipping cuDNN setup.")
        return

    if sys.platform == "win32":
        torch_lib_dir = Path(torch.__file__).parent / "lib"
        if torch_lib_dir.exists():
            os.add_dll_directory(str(torch_lib_dir))
            print(f"[INFO] Added DLL directory: {torch_lib_dir}")
        else:
            print(f"[WARNING] Torch lib directory not found: {torch_lib_dir}")

    elif sys.platform == "linux":
        site_packages = Path(torch.__file__).resolve().parents[1]
        cudnn_dir = site_packages / "nvidia" / "cudnn" / "lib"

        if not cudnn_dir.exists():
            print(f"[ERROR] cudnn dir not found: {cudnn_dir}")
            return

        pattern = str(cudnn_dir / "libcudnn_cnn*.so*")
        matching_files = sorted(glob.glob(pattern))
        if not matching_files:
            print(f"[ERROR] No libcudnn_cnn*.so* found in {cudnn_dir}")
            return

        for so_path in matching_files:
            try:
                ctypes.CDLL(so_path, mode=ctypes.RTLD_GLOBAL)
                print(f"[INFO] Loaded: {so_path}")
            except OSError as e:
                print(f"[WARNING] Failed to load {so_path}: {e}")

```

This may work for you, if you don't want to export `LD_LIBRARY_PATH`
