### ISSUE TITLE
Add support for passing buffers to transcribe

### ISSUE THREAD

**Issue by royce-mathew** [guillaumekln/faster-whisper#20]
Being able to have an option to pass the audio buffer directly to `faster-whisper` instead of creating a file would be really great.

**Comment by guillaumekln** [comment]
Hi,

This is already possible. The `transcribe` method accepts file-like objects so you can wrap your buffer with [`io.BytesIO`](https://docs.python.org/3/library/io.html#binary-i-o).

For example, the code below reads the audio file into a buffer of bytes which is then passed to `transcribe`:

```python
import io

with open("audio.mp3", "rb") as audio_file:
    audio_bytes = audio_file.read()
    audio_file = io.BytesIO(audio_bytes)

segments, _ = model.transcribe(audio_file)
text = "".join(segment.text for segment in segments)
```

**Comment by royce-mathew** [comment]
Would it be possible to add support to pass the waveform as a numpy array directly to `transform` without creating a file? `whisper` currently allows you to pass the audio file or the audio waveform. For projects which listen to audio in realtime and try to transcribe the audio fast I think the option of being able to pass the waveform directly to transcribe would be really great

**Comment by guillaumekln** [comment]
Sure, that should be a simple change. Let me open a PR.

**Comment by AngryBacteria** [comment]
Hei there

I am testing this feature out and for some reason it does not work for my configuration. I upload a file with fastapi to my server. The server then passes the file Object (it is a spooled temporary file) to the faster-whisper transcribe method. If I try it that way I get an error. If I save the exact same file to the disk and then pass the file path to the transcribe method it works as expected. Do you have any idea why that could happen? I appreciate the help!

This is the code snippet:

```python
    def transcribe_file(self, file: UploadFile, language_code: AzureLanguageCode = None):
        segments, info = self.model.transcribe(
            file.file,
            beam_size=self.beam_size,
            vad_filter=self.useVad,
            language=get_whisper_language(language_code),
        )
        logger.info(
            f"Starting inference: Detected language {info.language} with probability {info.language_probability}"
        )
        logger.info(f"Audio duration [{info.duration}][{info.duration_after_vad}]")

        for segment in segments:
            logger.debug(f"Recognized: {segment.text}")
            yield getattr(segment, 'text', '')

        logger.info("Finished whisper audio-processing")
```

and this the error:
```
<tempfile.SpooledTemporaryFile object at 0x000001FF43873D30>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\app\utils\whisper_util.py", line 76, in transcribe_file
    segments, info = self.model.transcribe(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\faster_whisper\transcribe.py", line 258, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\faster_whisper\audio.py", line 46, in decode_audio
    with av.open(input_file, metadata_errors="ignore") as container:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\container\core.pyx", line 411, in av.container.core.open
  File "av\container\core.pyx", line 219, in av.container.core.Container.__cinit__
ValueError: Could not determine output format
INFO:     127.0.0.1:56371 - "POST /api/transcribe/file/whisper?diarization=false&language=de-CH HTTP/1.1" 200 OK
<tempfile.SpooledTemporaryFile object at 0x000001FF4D3881F0>
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\app\utils\whisper_util.py", line 76, in transcribe_file
    segments, info = self.model.transcribe(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\faster_whisper\transcribe.py", line 258, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\faster_whisper\audio.py", line 46, in decode_audio
    with av.open(input_file, metadata_errors="ignore") as container:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\container\core.pyx", line 411, in av.container.core.open
  File "av\container\core.pyx", line 219, in av.container.core.Container.__cinit__
ValueError: Could not determine output format
WARNING:  StatReload detected changes in 'app\utils\whisper_util.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
2023-11-04 17:51:21,858 - INFO - Shutting down the server
INFO:     Application shutdown complete.
INFO:     Finished server process [11960]
Created LangchainUtil
Created OpenAIUtil
Created AzureUtil
2023-11-04 17:51:25,734 - INFO - Created WhisperUtil [GPU support]
INFO:     Started server process [17860]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:56425 - "POST /api/transcribe/file/whisper?diarization=false&language=de-CH HTTP/1.1" 400 Bad Request
INFO:     127.0.0.1:56438 - "POST /api/transcribe/file/whisper?diarization=false&language=de-CH HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\app\utils\whisper_util.py", line 73, in transcribe_file
    segments, info = self.model.transcribe(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\faster_whisper\transcribe.py", line 258, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Programming\Web\lc2_ambispeech\backend_fastapi\venv\Lib\site-packages\faster_whisper\audio.py", line 46, in decode_audio
    with av.open(input_file, metadata_errors="ignore") as container:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\container\core.pyx", line 411, in av.container.core.open
  File "av\container\core.pyx", line 219, in av.container.core.Container.__cinit__
ValueError: Could not determine output format
```

**Comment by rabyunghwa** [comment]
> Hi,
> 
> This is already possible. The `transcribe` method accepts file-like objects so you can wrap your buffer with [`io.BytesIO`](https://docs.python.org/3/library/io.html#binary-i-o).
> 
> For example, the code below reads the audio file into a buffer of bytes which is then passed to `transcribe`:
> 
> import io
> 
> with open("audio.mp3", "rb") as audio_file:
>     audio_bytes = audio_file.read()
>     audio_file = io.BytesIO(audio_bytes)
> 
> segments, _ = model.transcribe(audio_file)
> text = "".join(segment.text for segment in segments)

Hi. I might be totally wrong but IMHO that approach worked only because the mp3 audio file includes not just the audio byte array data but also some other metadata. How do I make it work if I simply pass in the audio byte array data captured from a mic? Like how do I achieve real-time transcription of audio streaming? How should the audio data be pre-processed before handing it to Whisper for transcription? I ran into this error:

> <built-in method with_traceback of InvalidDataError object at 0x7b251c541f60>
