### ISSUE TITLE
Cannot pip install from source on pypi

### ISSUE THREAD

**Issue by tomfuture** [guillaumekln/faster-whisper#239]
`pip install --no-binary` fails. It looks like this is because `requirements.txt` is missing from the source distribution tar archive at https://pypi.org/project/faster-whisper/#files.
Looking at setup.py, I think `requirements.conversion.txt` also needs to be included. It's not in the tarfile either.
Could you update pypi to include these files?

```
$ pip install --no-binary faster-whisper faster-whisper
Collecting faster-whisper
  Downloading faster-whisper-0.5.1.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 18.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/t/temp/faster-whisper-source/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/t/temp/faster-whisper-source/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/t/temp/faster-whisper-source/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-5xq9gyu6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-5xq9gyu6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-5xq9gyu6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-5xq9gyu6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 19, in <module>
        File "<string>", line 15, in get_requirements
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ugd4hpy_/faster-whisper_5f58a8920ea34e67a52797c9fdd6fb59/requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
$
```

**Comment by guillaumekln** [comment]
Thanks for reporting the issue.

However, even after fixing this specific error, source installation is currently not possible because some dependencies do not provide a source distribution:
* `ctranslate2`: https://pypi.org/project/ctranslate2/#files
* `onnxruntime`: https://pypi.org/project/onnxruntime/#files
