### ISSUE TITLE
Multi-gpu leads to `RuntimeError: CUDA failed with error invalid argument`

### ISSUE THREAD

**Issue by chainyo** [guillaumekln/faster-whisper#323]
I'm trying to run a FastAPI web server using `faster-whisper` on 4 different GPUs.

Here is my `TranscribeService` handler that loads 4 times a model on a different GPU using an index to know which one to load the model:

```python
class TranscribeService:
    """Transcribe Service for audio files."""

    def __init__(
        self,
        model_path: str,
        compute_type: str,
        device: str,
        device_index: Union[int, List[int]],
    ) -> None:
        """Initialize the Transcribe Service."""
        self.device = device
        self.compute_type = compute_type
        self.model_path = model_path
        self.models = {}

        for idx in device_index:
            model = WhisperModel(
                self.model_path,
                device=self.device,
                device_index=idx,
                compute_type=self.compute_type,
            )
            self.models[idx] = FasterWhisperModel(model=model, lang="multi")
        logger.debug(f"Loaded {len(self.models)} models for transcription.")
        
        [...]
```

On my 4xGPU serve,r each GPU should have a model loaded at the end of the init phase.
For inference, I have a `GPUService` which handles the GPU index attribution for a transcription job:

```python
class GPUService:
    """GPU service class to handle gpu availability for models."""
    def __init__(self, device: str, device_index: List[int]) -> None:
        """
        Initialize the GPU service.

        Args:
            device (str): Device to use for inference. Can be "cpu" or "cuda".
            device_index (List[int]): Index of the device to use for inference.
        """
        self.device: str = device
        self.device_index: List[int] = device_index

        # Initialize the models dictionary that will hold the models for each GPU.
        self.models: Dict[int, Any] = {}

        self.queue_lock = asyncio.Lock()
        self.queue = asyncio.Queue(maxsize=len(self.device_index))
        for idx in self.device_index:
            self.queue.put_nowait(idx)
        

    async def get_device(self) -> int:
        """
        Get the next available device.

        Returns:
            int: Index of the next available device.
        """
        async with self.queue_lock:
            device_index = await self.queue.get()

        return device_index

    def release_device(self, device_index: int) -> None:
        """
        Return a device to the available devices list.

        Args:
            device_index (int): Index of the device to add to the available devices list.
        """
        self.queue.put_nowait(device_index)
```

And here is the inference code:

```python
    def __call__(
        self,
        audio: Union[str, torch.Tensor, Tuple[str, str]],
        source_lang: str,
        model_index: int,
        suppress_blank: bool = False,
        word_timestamps: bool = True,
    ) -> List[dict]:
        """Run inference with the selected transcribe model."""
        segments, _ = self.models[model_index].model.transcribe(
            audio,
            language=source_lang,
            suppress_blank=False,
            word_timestamps=True,
        )

        outputs = [segment._asdict() for segment in segments]
        
        return outputs
```

The behavior of the `.generate()` method is weird because if I send 8 transcription jobs, they are handled correctly, and I get a 200 response with the transcribed outputs. But the following 4 requests will fail, 2-3 requests will be successful, and others will fail, etc. After a good inference process, I get only 50% of the successful requests.

Here is the full traceback:

```
Traceback (most recent call last):
  File "/app/wordcab_transcribe/services/asr_service.py", line 254, in process_transcription
    segments = self.services["transcription"](
  File "/app/wordcab_transcribe/services/transcribe_service.py", line 385, in __call__
    outputs = [segment._asdict() for segment in segments]
  File "/app/wordcab_transcribe/services/transcribe_service.py", line 385, in <listcomp>
    outputs = [segment._asdict() for segment in segments]
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 397, in generate_segments
    ) = self.generate_with_fallback(encoder_output, prompt, tokenizer, options)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 597, in generate_with_fallback
    result = self.model.generate(
RuntimeError: CUDA failed with error invalid argument
```

I'm running the server on NVIDIA T4. Are there any known issues with T4? I plan to try V100 later.
This behavior is btw really strange.

**Comment by guillaumekln** [comment]
Can you share a standalone code snippet to reproduce the error?

**Comment by chainyo** [comment]
This is the standalone code snippet with the minimal code and maximal abstraction possible. The main difference is we aren't running a web server (FastAPI) here, but the process is the same.

The problem is I don't get the same error here 😢 
So I can't reproduce the weird behavior.

```python
import asyncio
import functools
from typing import Any, Dict, List

import torch
from faster_whisper import WhisperModel


class GPUService:
    """GPU service class to handle gpu availability for models."""
    def __init__(self, device: str, device_index: List[int]) -> None:
        """
        Initialize the GPU service.

        Args:
            device (str): Device to use for inference. Can be "cpu" or "cuda".
            device_index (List[int]): Index of the device to use for inference.
        """
        self.device: str = device
        self.device_index: List[int] = device_index

        # Initialize the models dictionary that will hold the models for each GPU.
        self.models: Dict[int, Any] = {}

        self.queue_lock = asyncio.Lock()
        self.queue = asyncio.Queue(maxsize=len(self.device_index))
        for idx in self.device_index:
            self.queue.put_nowait(idx)
        

    async def get_device(self) -> int:
        """
        Get the next available device.

        Returns:
            int: Index of the next available device.
        """
        while True:
            try:
                device_index = self.queue.get_nowait()
                return device_index
            except asyncio.QueueEmpty:
                await asyncio.sleep(1.0)

    def release_device(self, device_index: int) -> None:
        """
        Return a device to the available devices list.

        Args:
            device_index (int): Index of the device to add to the available devices list.
        """
        self.queue.put_nowait(device_index)

class TranscribeService:
    """Transcribe Service for audio files."""
    def __init__(
        self, model_path: str, compute_type: str, device: str, device_index: List[int],
    ) -> None:
        """Initialize the Transcribe Service."""
        self.device = device
        self.compute_type = compute_type
        self.model_path = model_path
        self.models = {}

        for idx in device_index:
            model = WhisperModel(
                self.model_path,
                device=self.device,
                device_index=idx,
                compute_type=self.compute_type,
            )
            self.models[idx] = model

    def __call__(
        self, audio: str, source_lang: str, model_index: int,
    ) -> List[dict]:
        """Run inference with the selected transcribe model."""
        segments, _ = self.models[model_index].transcribe(
            audio,
            language=source_lang,
            suppress_blank=False,
            word_timestamps=True,
        )

        outputs = [segment._asdict() for segment in segments]
        
        return outputs


if __name__ == "__main__":
    device = "cuda" if torch.cuda.is_available() else "cpu"
    _n_gpus = torch.cuda.device_count() if device == "cuda" else 0
    device_index = list(range(_n_gpus))
    print(f"Using {device} with {len(device_index)} GPUs.")
    
    gpu_service = GPUService(device=device, device_index=device_index)
    print("GPU service initialized.")
    transcribe_service = TranscribeService(
        model_path="large-v2",
        compute_type="float16",
        device=device,
        device_index=device_index,
    )

    async def inference(audio: str, source_lang: str) -> List[dict]:
        """Transcribe audio file."""
        device_index = await gpu_service.get_device()

        loop = asyncio.get_event_loop()
        outputs = await loop.run_in_executor(
            None, functools.partial(
                transcribe_service, audio, source_lang, device_index
            )
        )
        gpu_service.release_device(device_index)

        return outputs

    async def main() -> None:
        """Launch multiple inference tasks in parallel."""
        tasks = []
        print("Starting inference tasks.")
        for _ in range(16):
            tasks.append(inference("data/sample.mp3", "fr"))

        # Now you can perform any post-processing or analysis on the results if needed
        for task in asyncio.as_completed(tasks):
            try:
                await task
                print("Task done.")
            except Exception as e:
                print(f"An error occurred: {e}")

    asyncio.run(main())
```

**Comment by chainyo** [comment]
> What version of `ctranslate2` was installed when the error occurred? Note that the same error was reported in #75, but it was fixed some time ago.

I'm running these versions: `ctranslate2==3.16.0` and `faster-whisper==0.6.0`

**Comment by neoyxm** [comment]
> 

@chainyo 

I had the same error even downgrading the ctranslate2 to 3.10.2 .

After dedugging, I found:

Don't create 4 models for your 4 devices. 
Just  create one model, and set the device list and num_workers to it:
`
 WhisperModel(...
     device_index=[0,1,2,3], 
     num_workers=4
...)
`

**Comment by chainyo** [comment]
> Don't create 4 models for your 4 devices. Just create one model, and set the device list and num_workers to it: `WhisperModel(... device_index=[0,1,2,3], num_workers=4 ...)`

Hi @neoyxm thanks for the hint. This is what I'm doing right now. But initially, I wanted to be able to load specific models for specific languages on one gpu to avoid unloading the model on all gpus.

**Comment by neoyxm** [comment]
> > Don't create 4 models for your 4 devices. Just create one model, and set the device list and num_workers to it: `WhisperModel(... device_index=[0,1,2,3], num_workers=4 ...)`
> 
> Hi @neoyxm thanks for the hint. This is what I'm doing right now. But initially, I wanted to be able to load specific models for specific languages on one gpu to avoid unloading the model on all gpus.

@chainyo  

I didn't meet such issue on centos 7.6 with  driver 460  and cuda 11.0 .

After upgrading the OS to Ubuntu 18.04(driver 515 & cuda 11.7),  the issue came up. 

I guess there is a certain pip package has broken it.

**Comment by guillaumekln** [comment]
Can you check if you also reproduce the error with `ctranslate2==3.16.1`?

It contains a [fix](https://github.com/OpenNMT/CTranslate2/commit/332cb6da956b30c7501980a96340881e7429f4a5) which prevents some Whisper inputs to be unexpectedly copied. This could explain this error if the input is on a specific CUDA device, but the copy occurs when the device has not been properly assigned. Can you check that?

**Comment by guillaumekln** [comment]
I assume this is no longer an issue. Feel free to reopen if you still get this error with recent versions of CTranslate2.

**Comment by chainyo** [comment]
Hi @guillaumekln, sorry for the late answer. I haven't tested it again for now. I let ctranslate2 use all the GPUs with the multi-GPU feature, but I'm not assigning one GPU anymore and exchanging when specific languages are required. I could test it again in the near future and ask for re-opening this issue if needed.

Thank you for your time.

**Comment by Wan9xy** [comment]
Hey, the problem happend on me, and when I remove vad_parameters, the program is running normal

**Comment by johnny8804130227** [comment]
> Hey, the problem happend on me, and when I remove vad_parameters, the program is running normal

Hello, may I ask which vad_parameters you are referring to?
My current solution is to run one GPU per process, avoiding the issue of a single process switching GPUs.
