### ISSUE TITLE
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by fylls** [guillaumekln/faster-whisper#363]
traceback
```
Downloading (…)76dd09bd/config.json: 100%|█| 2.23k/2.23k [00:00
Downloading (…)d09bd/vocabulary.txt: 100%|█| 422k/422k [00:00<0
Downloading (…)d09bd/tokenizer.json: 100%|█| 2.13M/2.13M [00:01
Downloading model.bin: 100%|█| 145M/145M [01:59<00:00, 1.21MB/s
Traceback (most recent call last):
  File "/home/fyll/Documents/GitHub/voice/low-latency.py", line 41, in <module>
    model = faster_whisper.WhisperModel(whisperModel, device="cuda", compute_type="float16")
  File "/home/fyll/Documents/GitHub/voice/env/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 124, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version
```

**Comment by guillaumekln** [comment]
You should update your GPU driver.

**Comment by fylls** [comment]
How can I do so in Ubuntu? Sorry for the naivetè
Haven't found something useful online

**Comment by archive-r** [comment]
https://www.nvidia.com/download/index.aspx?lang=en-us

**Comment by guillaumekln** [comment]
I'm pretty sure you can find several guides and documentations on how to update the GPU driver.

But you will not get help here to do that. We can only assist with issues that are specific to the project.

**Comment by fylls** [comment]
got it thanks a lot

**Comment by olawalejuwonm** [comment]
How can i make the update on windows please?
