### ISSUE TITLE
AttributeError: module 'ctranslate2' has no attribute 'StorageView'

### ISSUE THREAD

**Issue by Geremia** [guillaumekln/faster-whisper#391]
```python
>>> from faster_whisper import WhisperModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/faster-whisper/lib64/python3.9/site-packages/faster_whisper/__init__.py", line 2, in <module>
    from faster_whisper.transcribe import WhisperModel
  File "/tmp/faster-whisper/lib64/python3.9/site-packages/faster_whisper/transcribe.py", line 75, in <module>
    class WhisperModel:
  File "/tmp/faster-whisper/lib64/python3.9/site-packages/faster_whisper/transcribe.py", line 357, in WhisperModel
    encoder_output: Optional[ctranslate2.StorageView] = None,
AttributeError: module 'ctranslate2' has no attribute 'StorageView'
```
I built `CTranslate2` from master and installed `faster-whisper` with `pip` (in a `venv`).

**Comment by guillaumekln** [comment]
This is not directly related to faster-whisper.

Can you open an issue in https://github.com/OpenNMT/CTranslate2 and post all the steps you followed to compile the package?

**Comment by Geremia** [comment]
@guillaumekln thanks
