### ISSUE TITLE
If can't decode audio stream from video file , raise tuple index error 

### ISSUE THREAD

**Issue by iorilu** [guillaumekln/faster-whisper#407]
I met this error a few times, later as I checked , the reason is can't decode audio stream from video https://github.com/guillaumekln/faster-whisper/blob/1562b02345c8587eff1c6694b28c7f91f5c20ec2/faster_whisper/audio.py#L18C5-L18C17 , maybe due to some format issue , some videos can be opened for playback, but can't decode audio.

for these kinds of errors , is it better to raise some exception 

so we can catch it and display some message for end user.

**Comment by guillaumekln** [comment]
Can you post the actual error and traceback you are getting? If you can also share the video file that produces the error that would be helpful.

**Comment by iorilu** [comment]
: tuple index out of range
Traceback (most recent call last):
    segments, info = model.transcribe(
  File "D:\scoop\apps\miniconda3\current\envs\v2sub-fastwhisper-dev\lib\site-packages\faster_whisper\transcribe.py", line 239, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
  File "D:\scoop\apps\miniconda3\current\envs\v2sub-fastwhisper-dev\lib\site-packages\faster_whisper\audio.py", line 51, in decode_audio
    for frame in frames:
  File "D:\scoop\apps\miniconda3\current\envs\v2sub-fastwhisper-dev\lib\site-packages\faster_whisper\audio.py", line 97, in _resample_frames
    for frame in itertools.chain(frames, [None]):
  File "D:\scoop\apps\miniconda3\current\envs\v2sub-fastwhisper-dev\lib\site-packages\faster_whisper\audio.py", line 84, in _group_frames
    for frame in frames:
  File "D:\scoop\apps\miniconda3\current\envs\v2sub-fastwhisper-dev\lib\site-packages\faster_whisper\audio.py", line 74, in _ignore_invalid_frames
    yield next(iterator)
  File "av\container\input.pyx", line 202, in decode
  File "av\container\input.pyx", line 134, in demux
  File "av\container\streams.pyx", line 117, in av.container.streams.StreamContainer.get
/
IndexError: tuple index out of range

https://github.com/guillaumekln/faster-whisper/assets/2059858/a876e7c4-ca52-4d00-8487-d5d0c7723fd9

**Comment by guillaumekln** [comment]
It looks like the file has no audio stream. Here the error raised by the FFmpeg CLI:

```
$ ffmpeg -i out.mp4 -ar 16000 -ac 1 -c:a pcm_s16le output.wav
[...]
Output file #0 does not contain any stream
```
