### ISSUE TITLE
RuntimeError: cuDNN failed with status CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by silvacarl2** [guillaumekln/faster-whisper#408]
getting this strange erorr for some reason:

RuntimeError: cuDNN failed with status CUDNN_STATUS_NOT_INITIALIZED

whisper-ctranslate2 --model large-v2 --language en --compute_type float16  --vad_filter True --output_format txt 12694263-Joan-Svarczkopf.mp3 
Estimating duration from bitrate, this may be inaccurate
Detected language 'English' with probability 1.000000
Traceback (most recent call last):
  File "/home/silvacarl/.local/bin/whisper-ctranslate2", line 8, in <module>
    sys.exit(main())
  File "/home/silvacarl/.local/lib/python3.8/site-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 527, in main
    result = transcribe.inference(
  File "/home/silvacarl/.local/lib/python3.8/site-packages/src/whisper_ctranslate2/transcribe.py", line 164, in inference
    for segment in segments:
  File "/home/silvacarl/.local/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 883, in restore_speech_timestamps
    for segment in segments:
  File "/home/silvacarl/.local/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 396, in generate_segments
    encoder_output = self.encode(segment)
  File "/home/silvacarl/.local/lib/python3.8/site-packages/faster_whisper/transcribe.py", line 573, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: cuDNN failed with status CUDNN_STATUS_NOT_INITIALIZED

any ideas?

i reinstalled again but i got the same error.

**Comment by silvacarl2** [comment]
fixed: pip3 install torch==1.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116

**Comment by silvacarl2** [comment]
rebuilt my image from scratch, fixed.
