### ISSUE TITLE
ctranslate2 version 3.9.0 has an error

### ISSUE THREAD

**Issue by sergioudi** [guillaumekln/faster-whisper#46]
Hi,

ctranslate2 version 3.9.0 has the error below, I solved the problem by fixing version 3.8.0 in the file: requirements.txt
```
Traceback (most recent call last):
  File "/usr/local/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/transformers.py", line 863, in main
    converter.convert_from_args(args)
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/transformers.py", line 99, in _load
    spec = loader(model, tokenizer)
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/transformers.py", line 154, in __call__
    self.set_config(spec.config, model, tokenizer)
  File "/usr/local/lib/python3.9/dist-packages/ctranslate2/converters/transformers.py", line 584, in set_config
    range(config.decoder_layers // 2, config.decoder_layers),
AttributeError: 'WhisperConfig' object has no attribute 'decoder_layers'
```

**Comment by guillaumekln** [comment]
Hi,

Can you post the conversion command you are running?

**Comment by guillaumekln** [comment]
I can reproduce this error when converting a Whisper model from a path on disk.

```
ct2-transformers-converter --model /path/to/whisper/model ...
```

This will be fixed with https://github.com/OpenNMT/CTranslate2/pull/1131.

Note that if you plan to use word-level timestamps with one of the official pretrained models, it is better to convert with the model name directly because the configuration is [tuned](https://github.com/OpenNMT/CTranslate2/blob/v3.9.0/python/ctranslate2/converters/transformers.py#L870-L986) for these models.

```
ct2-transformers-converter --model openai/whisper-large-v2 ...
```

**Comment by sergioudi** [comment]
Thanks,

I did the test, replacing the transformers.py file locally with the one you adjusted in: OpenNMT/CTranslate2 and it worked perfectly.
