### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by haveyouwantto** [guillaumekln/faster-whisper#50]
Got error when transcribing segments.
```
Traceback (most recent call last):
  File "E:\AI\faster-whisper\trans.py", line 102, in <module>
    gensrt(segments, output_file, True)
  File "E:\AI\faster-whisper\trans.py", line 55, in gensrt
    for i, segment in enumerate(segments):
  File "E:\AI\faster-whisper\faster_whisper\transcribe.py", line 389, in generate_segments    self.add_word_timestamps(
  File "E:\AI\faster-whisper\faster_whisper\transcribe.py", line 547, in add_word_timestamps
    alignment = self.find_alignment(tokenizer, text_tokens, mel, num_frames)
  File "E:\AI\faster-whisper\faster_whisper\transcribe.py", line 617, in find_alignment
    start_times = jump_times[word_boundaries[:-1]]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by guillaumekln** [comment]
The same error was reported in https://github.com/guillaumekln/faster-whisper/issues/12#issuecomment-1464871400 but I was not able to reproduce it.

Can you share an audio file that produces this error?

**Comment by David-Pye** [comment]
To confirm I independently get the same error at the end of audio. I also can't share the audio. Note that I get it non deterministically, some times it's fine and ends with a final word of a... or a.

**Comment by haveyouwantto** [comment]
Here's the content of `jump_times` and `word_boundaries` when this error occurs:
```python
# jump_times
[0.]
```

```python
# word_boundaries
[ 0  1  4  5  6  7  8  9 10 13 16 17 18 19 20 21 22 23 24 25 28 29 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 51 54 55 56 57 58 59 60 61
 62 63 66]
```

**Comment by guillaumekln** [comment]
Does the same file work when using word-level timestamps in openai/whisper?

**Comment by haveyouwantto** [comment]
Yes, it can run normally in original whisper. I'm using `large-v2` model

**Comment by guillaumekln** [comment]
Thanks for the info.

I found the issue. There is a small error in the DTW implementation in CTranslate2: https://github.com/OpenNMT/CTranslate2/pull/1136

I will release a new version soon.

**Comment by Okabintaro** [comment]
Not sure if this is helpful or not but I had a similar traceback and found out that setting `without_timestamps=True` causes it to happen randomly. As soon as I set it to False, it never came back.
So yeah maybe just me being dumb setting the parameter, could be unrelated. Maybe could be caught by the application library too.

Thanks for all your work btw. faster-whisper is really great!
