### ISSUE TITLE
convert whisper large v3 error

### ISSUE THREAD

**Issue by lxygoodjob** [guillaumekln/faster-whisper#555]
PS C:\Users\lxy> ct2-transformers-converter --model openai/whisper-large-v3 --output_dir C:\Users\lxy\Desktop\faster-whisper-v3 --copy_files added_tokens.json special_tokens_map.json tokenizer_config.json vocab.json  --quantization float16
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lxy\miniconda3\Scripts\ct2-transformers-converter.exe\__main__.py", line 7, in <module>
  File "C:\Users\lxy\miniconda3\Lib\site-packages\ctranslate2\converters\transformers.py", line 1919, in main
    converter.convert_from_args(args)
  File "C:\Users\lxy\miniconda3\Lib\site-packages\ctranslate2\converters\converter.py", line 50, in convert_from_args
    return self.convert(
           ^^^^^^^^^^^^^
  File "C:\Users\lxy\miniconda3\Lib\site-packages\ctranslate2\converters\converter.py", line 89, in convert
    model_spec = self._load()
                 ^^^^^^^^^^^^
  File "C:\Users\lxy\miniconda3\Lib\site-packages\ctranslate2\converters\transformers.py", line 137, in _load
    tokenizer = self.load_tokenizer(
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lxy\miniconda3\Lib\site-packages\ctranslate2\converters\transformers.py", line 159, in load_tokenizer
    return tokenizer_class.from_pretrained(model_name_or_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lxy\miniconda3\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 736, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lxy\miniconda3\Lib\site-packages\transformers\tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lxy\miniconda3\Lib\site-packages\transformers\tokenization_utils_base.py", line 1886, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lxy\miniconda3\Lib\site-packages\transformers\tokenization_utils_base.py", line 2073, in _from_pretrained
    raise ValueError(
ValueError: Non-consecutive added token '<|0.02|>' found. Should have index 50365 but has index 50366 in saved vocabulary.
PS C:\Users\lxy>

**Comment by lxygoodjob** [comment]
success after update transformers to 4.35.0
