### ISSUE TITLE
transcription error with certain file

### ISSUE THREAD

**Issue by git-eternal** [guillaumekln/faster-whisper#89]
Getting the following output when transcribing a sherlock holmes audio book

PS C:\Users\admin\Desktop\AI Speech> py test.py
Fetching 6 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<?, ?it/s]                                                                                                                                              0:00<?, ?it/s]
Estimating duration from bitrate, this may be inaccurate
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\AI Speech\test.py", line 13, in <module>
    segments, info = model.transcribe("sherlock.mp3", beam_size=5)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\faster_whisper\transcribe.py", line 200, in transcribe
    audio = decode_audio(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\faster_whisper\audio.py", line 42, in decode_audio
    for frame in frames:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\faster_whisper\audio.py", line 69, in _resample_frames
    for frame in itertools.chain(frames, [None]):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\faster_whisper\audio.py", line 56, in _group_frames
    for frame in frames:
  File "av\container\input.pyx", line 203, in decode
  File "av\packet.pyx", line 87, in av.packet.Packet.decode
  File "av\stream.pyx", line 172, in av.stream.Stream.decode
  File "av\codec\context.pyx", line 524, in av.codec.context.CodecContext.decode
  File "av\codec\context.pyx", line 427, in av.codec.context.CodecContext._send_packet_and_recv
  File "av\error.pyx", line 336, in av.error.err_check
av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input

This is the video I got it from, I used a site to convert it to an mp3: https://www.youtube.com/watch?v=kVtNXspLNXw

**Comment by guillaumekln** [comment]
Can you try downloading the video with another tool like [yt-dlp](https://github.com/yt-dlp/yt-dlp) and directly use the downloaded `.webm` file for transcription?

**Comment by guillaumekln** [comment]
Audio frames raising this error are now skipped in the latest version.
